language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
install:
  - rustup toolchain install nightly
  - rustup component add rustfmt-preview --toolchain nightly
  - cargo build --verbose
script:
  - cargo test --verbose
  - cargo +nightly fmt --all -- --check
